---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: jdk8
inputs:
- name: sagan-renderer-repo
outputs:
- name: build
caches:
- path: gradle
run:
  path: /bin/bash
  args:
  - -ec
  - |
    ${PWD}/sagan-renderer-repo/concourse/scripts/build-sagan-renderer.sh